# Generated by Django 3.1.2 on 2020-11-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='user',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='user',
            new_name='seller',
        ),
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
